name: plume_CI_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  specimin-evaluation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Replace with the Java version you need (e.g., 11, 16, etc.)
          distribution: 'adopt'  # Specify the distribution of Java (e.g., adopt, zulu, etc.)
          architecture: 'x64'  # Specify the architecture of Java (e.g., x64, x86)
          server-password: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for server password
          overwrite-settings: true  # Overwrite any existing settings
          check-latest: false  # Do not check for the latest version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
      - name: Display CSV Contents
        run: |
          echo "Contents of plume_list.csv:"
          cat plume_list.csv
      - name: Display CSV File Contents
        run: |
          cat /home/runner/work/specimin/specimin/plume_list.csv   
      - name: List Files for Debugging
        run: ls -R

      - name: Clone Project B
        run: |
          git clone https://github.com/NiharikaJamble/ASHE_Automated-Software-Hardening-for-Entrypoints ASHE
      - name: Update Config File in Project B
        run: |
          echo "specimin.tool.path=$(pwd)" >> ASHE/src/main/resources/config.properties
      - name: Make run_ashe_for_stats.py executable
        run: chmod +x ashe_scripts/run_ashe_for_stats.py

      - name: Run the script
        run: |
          python3 ashe_scripts/run_ashe_for_stats.py \
            $(pwd)/ASHE \
            $(pwd)/plume_list.csv \
            $(pwd)/CI_REPO_CLONE_SPACE_PLUME \
            $(pwd)/ASHE/src/main/resources/config.properties
            
      - name: Display Current Directory Again
        run: echo "Current directory:" $(pwd)
