name: specimin-evaluation_CI_with_Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  specimin-evaluation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Replace with the Java version you need (e.g., 11, 16, etc.)
          distribution: 'adopt'  # Specify the distribution of Java (e.g., adopt, zulu, etc.)
          architecture: 'x64'  # Specify the architecture of Java (e.g., x64, x86)
        # server-id: 'github'  # Specify the server ID (typically 'github')
        # server-username: ${{ github.actor }}  # Use GITHUB_ACTOR for server username
          server-password: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for server password
          overwrite-settings: true  # Overwrite any existing settings
          check-latest: false  # Do not check for the latest version
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt


      - name: Display CSV Contents
        run: |
          echo "Contents of Specimin_Eval_Project_List.csv:"
          cat Specimin_Eval_Project_List.csv

      - name: Display CSV File Contents
        run: |
          cat /home/runner/work/specimin/specimin/Specimin_Eval_Project_List.csv   

      - name: List Files for Debugging
        run: ls -R

      - name: Run ASHE and Specimin Analysis Scripts
        run: |
          chmod +x ashe_scripts/run_ashe_for_stats.py
          chmod 644 Specimin_Eval_Project_List.csv
          python3 ashe_scripts/run_ashe_for_stats.py \
            $(pwd)/ASHE \
            $(pwd)/Specimin_Eval_Project_List.csv \
            $(pwd)/CI_REPO_CLONE_SPACE \
            $(pwd)ASHE/src/main/java/edu/njit/jerse/config/Configuration.java

            

      - name: Display Current Directory Again
        run: echo "Current directory:" $(pwd)


